### PR TITLE
Wording change: Add types to all internal algorithm members

### PR DESCRIPTION
**Pull request by inexorabletash**
Note that this isn't TypeScript or C++ - we are free to make the type annotations more specific, easier to read, etc. So there may be cases where we don't simply give an Infra or Web IDL type or rigorously follow the Infra style. Comments and suggestions welcome!

***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/536.html" title="Last updated on Jan 27, 2024, 6:57 PM UTC (7cc1a6e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/536/479ce17...inexorabletash:7cc1a6e.html" title="Last updated on Jan 27, 2024, 6:57 PM UTC (7cc1a6e)">Diff</a>

### CODE REVIEW

**Comment by inexorabletash** [comment]
One potential point of discussion - instead of just "string" e.g. in _"To create argMin/argMax operation given string op, ..."_ we could more specifically say "operator name". And we could go further and give a definition for that term ("A operator name is a string, used internally to distinguish similar operators..."), but that's overkill IMHO.

**Comment by huningxin** [comment]
> And we could go further and give a definition for that term ("A operator name is a string, used internally to distinguish similar operators...")

Or we can define an enum having all valid operator names? Maybe also overkill.

**Review by huningxin — COMMENTED** [review]
LGTM, thanks much!

**Review by huningxin — APPROVED** [review]

**Review by anssiko — APPROVED** [review]
👍

**Comment by inexorabletash** [comment]
And just to be pedantic: I now have _Triage_ permissions (thanks!) but not _Write_ permissions, so I still need an editor (etc) to hit the Merge button even if a PR has multiple approvals. Thanks in advance @wchao1115 😄

**Comment by anssiko** [comment]
I will merge this last open "wording change" ready-to-merge PR to let @wchao1115 focus his attention on PRs that propose normative changes.

I will ask @inexorabletash to give an overview of the recent wording change PRs on our upcoming meeting to ensure the entire WG is informed of changes that go in.

**Pull request merged**
