### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by anssiko**
Depends on https://github.com/tabatkins/bikeshed/pull/1718

### CODE REVIEW

**Comment by anssiko** [comment]
FYI editors @huningxin @wchao1115: if you use local bikeshed, [update bikeshed to its latest version](https://tabatkins.github.io/bikeshed/#updating-bikeshed) after the dependency lands.

**Comment by wchao1115** [comment]
@anssiko What else can I say? The logo looks great!

**Comment by anssiko** [comment]
Dependency landed, merging.

**Comment by anssiko** [comment]
(Note to self: We currently hardcode the same logo URL in bikeshed logo.include shared by all specs in this CG to give a common visual identity. Should we want to e.g. use a per spec logo or combine this logo with e.g. W3C organizational logo in the future, use the `[LOGO]` text macro in the appropriate bikeshed boilerplate includes to refer to the Logo URL defined in this spec locally.)

**Comment by anssiko** [comment]
Thanks! I figured out the exciting technical work happening in this group by its participants asked for a visual identity.

FTR, we’ve used this logo on our landing page https://webmachinelearning.github.io/ and as our GH org avatar from the very beginning since Oct 2018: https://github.com/webmachinelearning/webmachinelearning.github.io/commit/b0187352a2730968c26d0b71404463ca5682a190 At that time, the license was CC0. In Jan 2019, Pixabay changed its license to a CC0 derivative called ”Pixabay License”, which still seems fine for our purposes. Details: https://github.com/webmachinelearning/webmachinelearning.github.io/commit/0c4e7acf297d3df44b87e9eccb404f6fe63c85fe

However, once a CC0 license is applied, it is irrevocable, thus this logo is technically still under CC0. IANAL.

**Pull request merged**
