### PR TITLE
Style: Consistently use backticks for expressions in prose

### PR DESCRIPTION
**Pull request by inexorabletash**
Outside of algorithms, the spec is mostly consistent about formatting expressions using `backticks`; tidy up the few exceptions and add a convention note.

Also, apply the existing convention to format tensor shape definitions using *[ ... ]* consistently.

Also also, since it commonly precedes an expression, fix "as follow" to be "as follows" - the latter is the correct English form for this phrase, per style guides, even if multiple items follow it.

***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/710.html" title="Last updated on Jun 26, 2024, 7:10 PM UTC (cf6188a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/710/f7ceef9...inexorabletash:cf6188a.html" title="Last updated on Jun 26, 2024, 7:10 PM UTC (cf6188a)">Diff</a>

### CODE REVIEW

**Comment by inexorabletash** [comment]
Really, really minor cleanup. Please take a look?

**Review by anssiko — APPROVED** [review]

**Review by fdwr — APPROVED** [review]
👍

**Comment by inexorabletash** [comment]
@huningxin can you please review and merge if this looks okay? Thanks!

**Review by huningxin — APPROVED** [review]
LGTM!

**Pull request merged**
