### PR TITLE
Bug fix: Correct a handful of typos/JS errors in decompositions

### PR DESCRIPTION
**Pull request by inexorabletash**
Typos of "builder", incorrect arrow function syntax.

No normative changes.

***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/699.html" title="Last updated on Jun 4, 2024, 6:21 AM UTC (ee12205)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/699/91e2407...inexorabletash:ee12205.html" title="Last updated on Jun 4, 2024, 6:21 AM UTC (ee12205)">Diff</a>

### CODE REVIEW

**Review by zolkis — APPROVED** [review]
Looks good, thanks!

**Review by fdwr — APPROVED** [review]
👍

**Review by huningxin — APPROVED** [review]
LGTM!

**Comment by huningxin** [comment]
@inexorabletash , could you please resolve the merge conflicts? So, I can merge it, thanks!

**Comment by inexorabletash** [comment]
Conflicts resolved (hopefully)  - going to bed now, I'll fix in the morning if you notice any glitches.

**Comment by inexorabletash** [comment]
Merge when you're ready!

**Pull request merged**
