### PR TITLE
Bugfix: Unbalanced autolink brackets

### PR DESCRIPTION
**Pull request by inexorabletash**
Introduced by me in 1d1b531a c761733a. Oops.

***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/616.html" title="Last updated on Mar 21, 2024, 8:52 PM UTC (1ed5e99)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/616/77696f7...inexorabletash:1ed5e99.html" title="Last updated on Mar 21, 2024, 8:52 PM UTC (1ed5e99)">Diff</a>

### CODE REVIEW

**Comment by inexorabletash** [comment]
@anssiko - maybe you can review this trivial fix?

And... maybe we can look into tools to catch these? Options that come to mind:
* Pre-commit script that greps for bad patterns in the Bikeshed source (would have caught this one) - pro: easy to author; con: hard to maintain and regexes are non-trivial; can't catch post-rendering problems
* Local script executed by the Makefile that greps for bad patterns in the HTML output (plausible) - pro: can catch post-rendering problems; con: validating HTML with grep is also non-trivial
* Local script executed by the Makefile that uses a DOM parser (like BeautifulSoup) to lint the rendered output - pro: can catch nearly everything; con: even more difficult to author
* Script in the rendered HTML page itself that introspects and emits visible / console warnings - pro: JS is easy, can operate on the rendered output; con: can't automate, requires someone to look at output

I'm happy to tackle whichever if it'll improve our reliability and velocity.

**Review by anssiko — APPROVED** [review]
LGTM!

**Comment by anssiko** [comment]
Do you know if it’d be feasible for Bikeshed to catch these?

**Comment by inexorabletash** [comment]
> Do you know if it’d be feasible for Bikeshed to catch these?

There's been some discussion but the Bikeshed backlog is very, very long so I would not expect a quick fix.

**Comment by anssiko** [comment]
@inexorabletash thanks for checking. Regarding the options you listed, I'll let you pick your favourite in consultation with the editors. Any improvements that makes editing the spec less error prone, more enjoyable, even more fun, is always welcome!

**Review by huningxin — COMMENTED** [review]
LGTM, thanks for the fix.

**Pull request merged**
