### PR TITLE
void -> undefined for methods of 3.8. Execution

### PR DESCRIPTION
**Pull request by wonsuk73**
- Regarding to [Web IDL](https://heycam.github.io/webidl/), void should be changed with undefined.
- Additionally you can refer this, [void -> undefined, and allow it anywhere] (https://github.com/heycam/webidl/pull/906/)

### CODE REVIEW

**Comment by wonsuk73** [comment]
@huningxin @wchao1115 @anssiko could you review this?

**Comment by anssiko** [comment]
@wonsuk73 could you update index.bs and generate index.html per https://github.com/webmachinelearning/webnn#generating-the-specification and update this PR accordingly including both the index.bs and index.html changes in the commit? Thanks!

**Comment by wonsuk73** [comment]
@anssiko Thanks for your comment! I generated an index.html file using bikeshed as you said. But I think it updated the part of css of index.html file. So when I render index.html in chrome, spec's background color is black. It's strange. It's okay? or I need to do something else?

**Comment by wonsuk73** [comment]
I would like to close this commit and re-commit index.bs and index.html through bikeshed with new PR.

**Pull request closed without merging**
