### PR TITLE
void -> undefined for methods of 3.8. Execution 

### PR DESCRIPTION
**Pull request by wonsuk73**
- Regarding to [Web IDL](https://heycam.github.io/webidl/), void should be changed with undefined.
- Additionally you can refer this, [void -> undefined, and allow it anywhere] (https://github.com/heycam/webidl/pull/906/)

***
<a href="https://pr-preview.s3.amazonaws.com/wonsuk73/webnn/pull/100.html" title="Last updated on Oct 4, 2020, 12:53 AM UTC (325e1e4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/100/d740b23...wonsuk73:325e1e4.html" title="Last updated on Oct 4, 2020, 12:53 AM UTC (325e1e4)">Diff</a>

### CODE REVIEW

**Comment by wonsuk73** [comment]
@huningxin @wchao1115 @anssiko could you review this?
Note: Sorry for 3 commits because of "Revert" two times after the first commit.

**Comment by huningxin** [comment]
Thanks @wonsuk73 for this fix. I believe after #94 merged, this issue should be fixed. Could you please double check?

**Comment by wchao1115** [comment]
@wonsuk73 After PR#94 there is no more method returning void. I believe you can safely abandon this PR.

**Comment by wonsuk73** [comment]
@huningxin @wchao1115 Thanks for comment. I agreed with you comments

**Pull request closed without merging**
