### PR TITLE
Wording: Use shorter possessive form for abstract object properties

### PR DESCRIPTION
**Pull request by inexorabletash**
As discussed in https://github.com/webmachinelearning/webnn/pull/555#discussion_r1483911739    
    
* Old and busted: ... the [=property=] of |object| ...
* New hotness: ... |object|'s [=property=] ...

While making this change (which was mostly automated) I noticed a handful of very intertwined glitches; I included fixes as separate commits in this PR, to avoid too many PRs. They are:

* Correct a few cases of _"rank of op's shape"_ to just _"rank of op"_ (shapes have a size, operands have a rank)
* Fix some duplicated words
* Referencing _descriptor_ properties, but directly against an _operand_. 
* A few case where the simplification in 8503e2487126803a66cd870192657093dc16cb48 was missed.

I can split them out if desired.

***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/565.html" title="Last updated on Feb 15, 2024, 4:36 PM UTC (1d5d7aa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/565/745ddbc...inexorabletash:1d5d7aa.html" title="Last updated on Feb 15, 2024, 4:36 PM UTC (1d5d7aa)">Diff</a>

### CODE REVIEW

**Review by fdwr — APPROVED** [review]
✨🔥 Farewell "the the" and "as as".

**Review by anssiko — APPROVED** [review]

**Comment by anssiko** [comment]
@inexorabletash much thanks! Ready to merge when the conflicts have been resolved.

**Comment by inexorabletash** [comment]
Resolved - @anssiko please double check and merge at your leisure!

**Comment by anssiko** [comment]
Still looks as good as earlier and the build is 🟢 so... let's squash and merge!

**Pull request merged**
