### PR TITLE
Update newShape with null value for reshape operation

### PR DESCRIPTION
**Pull request by BruceDai**
@huningxin @anssiko PTAL, thanks.

***
<a href="https://pr-preview.s3.amazonaws.com/BruceDai/webnn/pull/367.html" title="Last updated on Mar 23, 2023, 9:37 AM UTC (db53c2f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/367/d3cc570...BruceDai:db53c2f.html" title="Last updated on Mar 23, 2023, 9:37 AM UTC (db53c2f)">Diff</a>

### CODE REVIEW

**Comment by anssiko** [comment]
Is there a corresponding issue that this PR proposes to fix?

**Comment by BruceDai** [comment]
> Is there a corresponding issue that this PR proposes to fix?

Yes, this pr is also to fix https://github.com/webmachinelearning/webnn/issues/289, thanks.

**Comment by anssiko** [comment]
@wacky6 PTAL if this PR fixes issue #289 you identified.

Thanks @BruceDai for the PR!

**Review by wacky6 — APPROVED** [review]

**Comment by fdwr** [comment]
@BruceDai : Yeah, I like `null` more than I do `-1` as a sort of wildcard (and that enables using tensors greater than 2147483647 elements, per the issue you linked to).

Though also, is this some behavior something that can be easily resolved by the frameworks calling into WebNN, since presumably they already know the shapes along the way and could instead pass concrete values to WebNN?

**Review by fdwr — APPROVED** [review]

**Review by huningxin — APPROVED** [review]

**Review by wchao1115 — APPROVED** [review]

**Comment by huningxin** [comment]
Thanks for the review and approvals. Let's merge this PR.

**Pull request merged**
