### PR TITLE
Replaced interface with partial interface in WebIDL

### PR DESCRIPTION
**Pull request by wonsuk73**
- For all of WebIDL definition in this spec, partial interface probably need to be used rather then interface according to WebIDL spec [1]
- Because the definition of an interface is separated over more than one section of the document
[1] https://heycam.github.io/webidl/

### CODE REVIEW

**Comment by anssiko** [comment]
Thanks for reviewing this spec @wonsuk73! Please note the duplicate occurrences of the following interfaces you flagged are found in the [IDL Index section](https://webmachinelearning.github.io/webnn/#idl-index):

interface ML
interface Operand
interface Model
interface Compilation
interface Execution

The IDL Index section is Bikeshed-generated boilerplate that concatenates all IDL blocks from the spec together. That is a Bikeshed feature and not a bug :) I'll let spec editors @huningxin @wchao1115 confirm and check our IDL usage is correct in this regard.

We use partial interface extensively for NeuralNetworkContext that hosts the definitions of a number of operations, and that usage seems valid to me.

**Comment by wonsuk73** [comment]
Thanks for quick review @anssiko. I think most of your comments are right. and I misunderstood some part of WebDIL spec.
But I think [interface NeuralNetworkContext](https://webmachinelearning.github.io/webnn/#neuralnetworkcontext) need to be  replaced with partial interface because that define part of NeuralNetworkContext interface. Am I right?

**Comment by anssiko** [comment]
I think that is the first occurrence of the NeuralNetworkContext interface, so only subsequent occurrences of the same interface need partial. We should have those covered, but better doublecheck.

**Comment by wonsuk73** [comment]
@anssiko Thanks! You are completely right! I think I need to withdraw this PR.

**Pull request closed without merging**
