### PR TITLE
Use unsigned long for size related options of conv2d, convTranspose2d and pooling operations

### LINKED ISSUE #269: Define the data type of the padding, strides and dilations of MLConv2dOptions as sequence<unsigned long>
The data type of padding, strides and dilations of [MLConv2dOptions](https://webmachinelearning.github.io/webnn/#dictdef-mlconv2doptions) are defined as `sequence<long>` now. When we implement the backends of WebNN, we found that the data type of these arguments were defined differently by each backend. In fact, there is no need to use negative value for these three arguments, unlike `axis` in [MLSplitOptions](https://webmachinelearning.github.io/webnn/#dictdef-mlsplitoptions). So should we use `sequence<unsigned long>` to define these three arguments?

Backend | Data Type
-- | --
OpenVINO | int32
DirectML | uint32
MLAS | int64
XNNPack | uint32
OneDNN | int64
NNAPI | int32

### PR DESCRIPTION
**Pull request by huningxin**
There are no use cases for negative values of these attributes including:
- MLConv2dOptions: padding, strides, dilations and groups.
- MLConvTranspose2dOptions: padding, strides, dilations, outputPadding, outputSizes and groups.
- MLPool2dOptions: windowDimensions, padding, strides, dilations and outputSizes.

fix #269

@wchao1115 @anssiko @wacky6 @miaobin, PTAL. Thanks!

***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/294.html" title="Last updated on Dec 16, 2022, 8:36 AM UTC (9c2e9fa)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/294/393cd2a...huningxin:9c2e9fa.html" title="Last updated on Dec 16, 2022, 8:36 AM UTC (9c2e9fa)">Diff</a>

### CODE REVIEW

**Review by anssiko — APPROVED** [review]

**Review by wacky6 — APPROVED** [review]

**Comment by anssiko** [comment]
@wchao1115 can we merge this?

**Comment by anssiko** [comment]
@wchao1115 gentle ping, PTAL.

**Review by wchao1115 — APPROVED** [review]

**Comment by anssiko** [comment]
Thanks again @wchao1115!

@huningxin I addressed the merge conflict. PTAL and feel free to merge when you're good.

@brucedai for wpt test alignment.

**Comment by BruceDai** [comment]
@anssiko Thanks for your reminder, I got it.

**Comment by huningxin** [comment]
Thanks for the review and approval. Also thanks @anssiko for the rebasing. I am going to merge it.

**Pull request merged**
