### PR TITLE
Add the spec text and examples for MLGraph.compute

### LINKED ISSUE #140: NamedOutput mechanism clarification
> 10. I don't quite understand the NamedOutput mechanism. What if what is output just a feature?

via https://github.com/w3ctag/design-reviews/issues/570#issuecomment-768875996

@cynthia "What if what is output just a feature?" part needs a clarification?

### PR DESCRIPTION
**Pull request by huningxin**
@wchao1115 @pyu10055 @anssiko , PTAL.

Hopefully, it would fix #140 @cynthia, please also take a look.

Another note is, for the spec of ML device interactions, I found the [timelines](https://gpuweb.github.io/gpuweb/#programming-model-timelines) of WebGPU spec is quite useful. So I adapted and included it in this PR.

***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/147.html" title="Last updated on Apr 1, 2021, 3:13 PM UTC (380379c)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/147/880cd8a...huningxin:380379c.html" title="Last updated on Apr 1, 2021, 3:13 PM UTC (380379c)">Diff</a>

### CODE REVIEW

**Comment by anssiko** [comment]
@huningxin, thank you for this substantial PR. LGTM for the general direction.

I suggest we seek review from WebGPU folks for the timeline convention we've borrowing from the WebGPU spec. @kainino0x may be interested in taking a quick look on that particular aspect.

**Review by anssiko — APPROVED** [review]

**Comment by huningxin** [comment]
> I suggest we seek review from WebGPU folks for the timeline convention we've borrowing from the WebGPU spec. @kainino0x may be interested in taking a quick look on that particular aspect.

Absolutely, also cc @Kangz

**Review by wchao1115 — APPROVED** [review]

**Comment by huningxin** [comment]
Thanks for review, also @RafaelCintron for comments.

**Comment by huningxin** [comment]
I'll rework this PR due to #149 and potential change being discussed in https://github.com/webmachinelearning/webnn/pull/149#discussion_r594543292

**Comment by wchao1115** [comment]
@huningxin Can you update the PR to reflect the new naming in the spec?

**Comment by huningxin** [comment]
> @huningxin Can you update the PR to reflect the new naming in the spec?

@wchao1115 , done. Actually reworked this PR regarding to #149 . 

Please note this PR only specifies the `MLGraph.compute` algorithm steps for default context with inputs/outputs are `ArrayBufferView`. An issue was added inline into the spec that tracks the algorithm steps for WebGL/WebGPU interops.

Please take another look. Thanks!

**Review by pyu10055 — APPROVED** [review]

**Comment by huningxin** [comment]
The conflict was resolved, I am going to merge it, thanks for the review and approvals.

**Pull request merged**
