### PR TITLE
Wording: Fix some minor typos and grammar glitches

### PR DESCRIPTION
**Pull request by inexorabletash**
***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/782.html" title="Last updated on Nov 9, 2024, 12:59 AM UTC (e536886)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/782/11f85ff...inexorabletash:e536886.html" title="Last updated on Nov 9, 2024, 12:59 AM UTC (e536886)">Diff</a>

### CODE REVIEW

**Review by huningxin — APPROVED** [review]
LGTM! Thanks @inexorabletash !

**Comment by inexorabletash** [comment]
> LGTM! Thanks @inexorabletash !

I slipped one more commit in after your review - PTAL?

**Review by huningxin — APPROVED** [review]
Still LGTM!

**Review by fdwr — APPROVED** [review]
Thanks Josh. Farewell snaphots.

**Pull request merged**
