### PR TITLE
Add Makefile

### PR DESCRIPTION
**Pull request by huningxin**
If bikeshed is installed locally, execute:
$ make

Otherwise, execute:
$ make online=1

### CODE REVIEW

**Comment by huningxin** [comment]
@anssiko and @wchao1115 , could you please take a look? The Makefile would help the development process. Thanks!

**Comment by huningxin** [comment]
@anssiko , I've added the build instructions into the README.md in the new [commit](https://github.com/webmachinelearning/webnn/pull/56/commits/6e7d6408a8ea15345f3a876df74effce4db479cb). Please take a look. Thanks!

**Comment by anssiko** [comment]
LGTM. Thanks!

**Comment by huningxin** [comment]
Thanks for review. I am going to merge it so it can help others. If there are any bugs, please file issue I'll fix.

**Pull request merged**
