### PR TITLE
Remove softplus() steepness option

### LINKED ISSUE #645: Specify the behavior of sofplus when the steepness is 0
It's raised by @a-sully in [CL review](https://chromium-review.googlesource.com/c/chromium/src/+/5445810/3/third_party/blink/renderer/modules/ml/webnn/ml_graph_builder_test.cc#b2313), thanks!

Softplus calculates `ln(1 + exp(steepness * x)) / steepness`, when the steepness is 0 it might result in division by zero.

I tried Pytorch `torch.nn.Softplus(beta=0)` and the results are all inf, and [TF](https://www.tensorflow.org/api_docs/python/tf/math/softplus) and [ONNX](https://onnx.ai/onnx/operators/onnx__Softplus.html) don't have this attribute. Also [DirectML](https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_activation_softplus_operator_desc) doesn't support `steepness < 1.0`.

### PR DESCRIPTION
**Pull request by a-sully**
Fixes #645

***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/651.html" title="Last updated on Apr 22, 2024, 5:49 PM UTC (6a158b4)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/651/50fbb92...a-sully:6a158b4.html" title="Last updated on Apr 22, 2024, 5:49 PM UTC (6a158b4)">Diff</a>

### CODE REVIEW

**Comment by a-sully** [comment]
@fdwr PTAL?

**Comment by fdwr** [comment]
FYI @BruceDai since this affects conformance.
FYI @Honry, but I didn't see this impacts the ORT WebNN EP since you just pass default options anyway.

**Comment by Honry** [comment]
> FYI @Honry, but I didn't see this impacts the ORT WebNN EP since you just pass default options anyway.

Correct, we didn't use steepness option in WebNN EP.

**Comment by BruceDai** [comment]
OK, I will update WPT `softplus` tests to align with this change. Thanks for your kindly reminder  👍 @fdwr

**Review by huningxin — APPROVED** [review]
LGTM, thanks!

**Review by fdwr — APPROVED** [review]
👍 No pushback from my colleagues Chai or Rafael either.

**Pull request merged**
