### PR TITLE
Convert MLOperand methods into readonly attributes

### LINKED ISSUE #666: Reconsider `MLOperand` methods
The [`MLOperand`](https://webmachinelearning.github.io/webnn/#mloperand) interface looks like:

```diff
interface MLOperand {
  MLOperandDataType dataType();
  sequence<unsigned long> shape();
};
```

Each of these methods meets the criteria for being an attribute (https://w3ctag.github.io/design-principles/#attributes-vs-methods), and are [const](https://crsrc.org/c/third_party/blink/renderer/modules/ml/webnn/ml_operand.h;l=114-116;drc=53c1d06fee5a3e98e7f265419f6f84df2c2c2d62) once the `MLOperand` is constructed. Is we are to have an accessor on `MLOperand` for each key in the `MLOperandDescriptor` which created it, then these should be `readonly attribute`s.

That being said, once we open this can of worms, there are several options we could choose from:

### 1. Getter which returns an `MLOperandDescriptor`

```diff
interface MLOperand {
-  MLOperandDataType dataType();
-  sequence<unsigned long> shape();
+  MLOperandDescriptor descriptor();
};
```

This is my preferred option. Unfortunately, JavaScript dictionaries are not read-only so (unless we want to push to introduce `FrozenDictionary`) we should use a getter.

### 2. Naive conversion to `readonly attribute`

```diff
interface MLOperand {
-  MLOperandDataType dataType();
+  readonly attribute MLOperandDataType dataType;
-  sequence<unsigned long> shape();
+  readonly attribute sequence<unsigned long> shape;
};
```

Seems reasonable. But why have an attribute called `shape` which refers to the same thing as `MLOperandDescriptor.dimensions`?

### 3. Rename `shape` to `dimensions`, or vice versa

```diff
dictionary MLOperandDescriptor {
  required MLOperandDataType dataType;
-  sequence<[EnforceRange] unsigned long> dimensions = [];
+  sequence<[EnforceRange] unsigned long> shape = [];
};

interface MLOperand {
-  MLOperandDataType dataType();
+  readonly attribute MLOperandDataType dataType;
-  sequence<unsigned long> shape();
+  readonly attribute sequence<unsigned long> shape;
};
```

`MLOperandDescriptor` takes a `dimensions` field, while querying this field from an `MLOperand` is done with the `shape()` method. As per https://w3ctag.github.io/design-principles/#attribute-reuse, we should re-use terms rather than unnecessarily introducing new vocabulary.

A quick CTRL-F of the spec text shows:
- 139 instances of "dimensions", mostly due to `MLOperandDescriptor.dimensions`
- 483 instances of "shape", which seems to be used more commonly in prose (e.g. "the shape of the input tensor")

We should decide to use one or the other (and possibly continue this discussion on another issue regardless)

### 4. Make `MLOperandDescriptor` an `interface`

```diff
-dictionary MLOperandDescriptor {
+interface MLOperandDescriptor {
  required MLOperandDataType dataType;
  sequence<[EnforceRange] unsigned long> dimensions = [];
};

interface MLOperand {
-  MLOperandDataType dataType();
-  sequence<unsigned long> shape();
+  readonly attribute MLOperandDescriptor descriptor;
};
```

This is my least favorite, but I figured I'd list this here for completeness.

### PR DESCRIPTION
**Pull request by a-sully**
Fixes #666

Implements the changes proposed in https://github.com/webmachinelearning/webnn/issues/666#issuecomment-2342019337 while simplifying the declaration of these getters to use the pattern suggested in https://webidl.spec.whatwg.org/#idl-frozen-array

***
<a href="https://pr-preview.s3.amazonaws.com/a-sully/webnn/pull/774.html" title="Last updated on Oct 29, 2024, 8:32 PM UTC (a8b0b3d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/774/9287c0b...a-sully:a8b0b3d.html" title="Last updated on Oct 29, 2024, 8:32 PM UTC (a8b0b3d)">Diff</a>

### CODE REVIEW

**Comment by a-sully** [comment]
@fdwr this PR follows up on our recent thread on #666. I expect to migrate the Chromium implementation in the same way as the `dimensions` -> `shape` refactoring. PTAL?

**Comment by a-sully** [comment]
> I expect to migrate the Chromium implementation in the same way as the `dimensions` -> `shape` refactoring. PTAL?

Hmm unfortunately this style of migration may not be possible in this case, since the Blink bindings code doesn't support interfaces which have a method and an attribute of the same name. See the crashes in https://crrev.com/c/5975719

We can have getters or methods, but not both at the same time... so a migration period is not possible :/ 

Would you prefer to make this change now or later?

**Comment by fdwr** [comment]
> We can have getters or methods, but not both at the same time... so a migration period is not possible :/
> 
> Would you prefer to make this change now or later?

Well I'd like to frontload any breaking changes sooner than later, which smoothens the path to origin trial. However, if we can't mitigate this in any way on the Chromium end, can we closely synchronize the changes by having the corresponding update in samples already ready before completing the Chromium change?

@ibelem : For the [ORT-based samples](https://aka.ms/webnn), maybe we could update the sample logic to map a given Chromium version to a correspondingly compatible build of ORT, so there is implicitly a window of migration in the sample logic, even if Chromium breaks?

**Review by huningxin — APPROVED** [review]
LGTM

/cc @Honry @BruceDai for required changes in webnn-samples, webnn-baseline and tests.

**Review by fdwr — APPROVED** [review]
👍

**Pull request merged**
