### PR TITLE
Content: Clarify the expected behavior for axes being empty

### LINKED ISSUE #493: Clarify the expected behavior for `axes` being empty `[]`
Current Spec isn't clear for `axes` being empty `[]` for below operations.

op|
|---|
argMin/Max|
layerNormalization|
Reduction operations|
resample2d|

@fdwr explained this `axes=[]` for **argMin/Max** when his reviewing on [my baseline implementation](https://github.com/webmachinelearning/webnn-baseline/pull/62) like [the comment](https://github.com/webmachinelearning/webnn-baseline/pull/62#discussion_r1427551113) and also kindly demoed [the test cases of axes=[]](https://github.com/webmachinelearning/webnn-baseline/pull/62#discussion_r1427564488) (Thanks @fdwr! )

> If you pass axes = [], will that correctly use the explicit empty axes (output shape is then the same size as the input, and there is a 1:1 mapping of output indices) rather than generate full reduction?

> image
> image

### PR DESCRIPTION
**Pull request by inexorabletash**
The shape calculation for argMin/argMax and reduction ops is now fully specified, but the implied behavior of {axes:[]} for these ops and layerNormalization was not particularly clear.

Add a little text to make it clearer.

Fixes #493

***
<a href="https://pr-preview.s3.amazonaws.com/inexorabletash/webnn/pull/599.html" title="Last updated on Mar 13, 2024, 4:31 PM UTC (48fab65)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/599/1d1b531...inexorabletash:48fab65.html" title="Last updated on Mar 13, 2024, 4:31 PM UTC (48fab65)">Diff</a>

### CODE REVIEW

**Comment by inexorabletash** [comment]
@BruceDai can you take an initial look?

**Comment by BruceDai** [comment]
I apologize for my late response.

LGTM, thanks for these clarification texts.

**Comment by inexorabletash** [comment]
Thanks @BruceDai - and no worries. I'm generating a lot of review requests. @fdwr and @huningxin - please review/merge at your leisure!

**Review by huningxin — APPROVED** [review]
LGTM, thanks for the clarification!

**Review by fdwr — APPROVED** [review]
👍

**Pull request merged**
