### PR TITLE
Change newShape of reshape to a sequence of nullable unsigned long

### LINKED ISSUE #289: Reshape doesn't support full range of operand dimension size
According to #281 , now the [`MLOperandDescriptor.dimensions`](https://www.w3.org/TR/webnn/#api-mloperanddescriptor) is of type `sequence<unsigned long>` with supported dimension size range `[1, 4294967295]`. However, the [`reshape`](https://www.w3.org/TR/webnn/#api-mlgraphbuilder-reshape) op still supports the `newShape` of type `sequence<long>`. Except the special value `-1` for shape inference, the supported dimension size range is `[1, 2147483647]`. The user code is not able to reshape a tensor to a new shape with dimension size in the range `(2147483647, 4294967295]`. 

Thanks @wacky6 for raising this issue in [Chromium CL review](https://chromium-review.googlesource.com/c/chromium/src/+/3866751/comments/a02835ac_0fc1ae53).

### PR DESCRIPTION
**Pull request by huningxin**
fix #289

@wchao1115 @anssiko @wacky6, please take a look, thanks!

***
<a href="https://pr-preview.s3.amazonaws.com/huningxin/webnn/pull/291.html" title="Last updated on Sep 5, 2022, 6:43 AM UTC (80a3917)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/291/39951a0...huningxin:80a3917.html" title="Last updated on Sep 5, 2022, 6:43 AM UTC (80a3917)">Diff</a>

### CODE REVIEW

**Comment by wacky6** [comment]
This LGTM to me.

But please consider my comments here regarding edge cases in implementation: https://github.com/webmachinelearning/webnn/issues/289#issuecomment-1236638142

I can't think of better ideas. Coercion to uint32 here seems an unfortunate language feature of JavaScript.

**Review by anssiko — APPROVED** [review]
A null special case is good for symmerty with Torch and TF but I want to be on record it departs from the ONNX convention.

We should try to use these conventions consistently and align with existing ones when practical.

Thanks @wacky6 for reporting this IDL type bug.

**Comment by anssiko** [comment]
FWIW, TAG has some guidance on numeric types: https://www.w3.org/TR/design-principles/#numeric-types

I think WebNN for the most part falls into the ”specific reason not to” category due to its specialization.

**Comment by huningxin** [comment]
@wacky6 is asking whether this is still a v1 issue/PR in the corresponding Chromium implementation [review](https://chromium-review.googlesource.com/c/chromium/src/+/3969126/comment/c4f60be8_101fdb73/). I suppose it is. However, it has been on the WG meeting [agenda](https://github.com/webmachinelearning/meetings/blob/main/telcons/2022-10-20-wg-agenda.md#%E2%84%B9%EF%B8%8F-prs-in-review) for a while. @anssiko , if my understanding is correct, could we prioritize the pending v1 PRs review in our next meeting. Thanks!

**Review by wchao1115 — APPROVED** [review]

**Comment by anssiko** [comment]
@huningxin feel free to merge this unless new implementation experience has been gathered that'd suggest more refinement is needed.

**Comment by huningxin** [comment]
Thanks @anssiko for the remind. I am going to merge this one. Thanks all for your reviews and approvals.

**Pull request merged**
