### PR TITLE
Add int64, uint64 data type support for reduceL1, reduceProduct, reduceSum and reduceSumSquare

### LINKED ISSUE #694: Consider adding int64/uint64 data type support for some reduce operators
One safety checker SD model failed since 'reduceSum' which from Safety Checker requires int64 input type. And currently, WebNN spec only supports int32, uint32, float32 and float16 for reduceSum.

image

I suppose we should add int64 and uint64 data type for ReduceSum, ReduceSumSquare, ReduceProduct and ReduceL1 which is consistent with DirectML reduce operation definition: 
https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_reduce_operator_desc#multiply-and-sum  and  https://learn.microsoft.com/en-us/windows/win32/api/directml/ns-directml-dml_reduce_operator_desc#l1-and-sum_square.

### PR DESCRIPTION
**Pull request by shiyi9801**
Fixes #694

***
<a href="https://pr-preview.s3.amazonaws.com/shiyi9801/webnn/pull/750.html" title="Last updated on Aug 14, 2024, 6:53 AM UTC (dd714ab)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/webmachinelearning/webnn/750/d7d0363...shiyi9801:dd714ab.html" title="Last updated on Aug 14, 2024, 6:53 AM UTC (dd714ab)">Diff</a>

### CODE REVIEW

**Comment by shiyi9801** [comment]
Current Chromium implementation allows int64/uint64 for these reduce ops, so I think we should either change the spec or the implementation. PTAL, thanks :) @huningxin @fdwr

**Review by fdwr — APPROVED** [review]
opSupportLimits for CoreML will be negative for these ops, but LGTM. Thanks for spotting the difference.

**Comment by huningxin** [comment]
Thanks @shiyi9801 , is this PR duplicated by https://github.com/webmachinelearning/webnn/pull/695?

**Comment by fdwr** [comment]
> Thanks @shiyi9801 , is this PR duplicated by #695?

Aah yes, that did look familiar.

**Comment by shiyi9801** [comment]
> Thanks @shiyi9801 , is this PR duplicated by #695?

Oh I didn't notice there is already a PR to fix this, yes it is duplicated, please continue yours :) I'll drop this PR.

**Pull request closed without merging**
